name: Flatpak
on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up environment
        uses: mikefarah/yq@v4.8.0
        id: props
        env:
          TZ: America/Sao_Paulo
        run: |
          REPO_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
          echo ::set-output name=REPO_NAME::$REPO_NAME
          echo ::set-output name=SHA_SHORT::$(git rev-parse --short HEAD)
          echo ::set-output name=IRPF_VER::$(cat "$REPO_NAME.yaml" | yq e '.modules[] | select(.name == "irpf").sources[] | select(.url == "*IRPF*.zip").url' - | sed -r 's/.*IRPF([0-9.-]+)\.zip/\1/')
          echo ::set-output name=TODAY::$(date +'%Y%m%d')

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y flatpak-builder

      - name: Cache Flatpak SDK
        uses: actions/cache@v2
        with:
          key: forever
          path: |
            ~/.local/share/flatpak

      - name: Set up Flatpak
        run: |
          flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Build (x86_64)
        run: |
          flatpak-builder --user --arch=x86_64 --force-clean --install-deps-from=flathub --repo=repo/ --sandbox build/ "${{ steps.props.outputs.REPO_NAME }}.yaml"

      - name: Bundle (x86_64)
        run: |
          flatpak build-bundle --arch=x86_64 repo/ x86_64.flatpak "${{ steps.props.outputs.REPO_NAME }}" stable

      - name: Upload (x86_64)
        uses: actions/upload-artifact@v2
        with:
          name: IRPF_v${{ steps.props.outputs.IRPF_VER }}-${{ steps.props.outputs.TODAY }}-${{ steps.props.outputs.SHA_SHORT }}-x86_64.flatpak
          path: |
            *.flatpak
            