name: Flatpak
on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y flatpak-builder

      - name: Set up Flatpak
        run: |
          flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Build (x86_64)
        run: |
          flatpak-builder --user --arch=x86_64 --force-clean --install-deps-from=flathub --repo=repo/ --sandbox build/ br.gov.economia.receita.IRPF.yaml

      - name: Bundle (x86_64)
        run: |
          flatpak build-bundle --arch=x86_64 repo/ "IRPF_${{ env.RELEASE_VERSION }}-${{ github.sha }}.flatpak" br.gov.economia.receita.IRPF stable

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: irpf-x86_64
          path: *.flatpak
            