name: Flatpak
on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up variables
        id: vars
        env:
          TZ: America/Sao_Paulo
        run: |
          echo ::set-output name=REPO_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
          echo ::set-output name=SHA_SHORT::$(git rev-parse --short HEAD)
          echo ::set-output name=TODAY::$(date +'%Y%m%d')

      - name: Grab IRPF version
        id: irpf
        uses: mikefarah/yq@v4.8.0
        with:
          cmd: |
            echo ::set-output name=VERSION::$(cat "${{ steps.vars.outputs.REPO_NAME }}.yaml" | yq e '.modules[] | select(.name == "irpf").sources[] | select(.url == "*IRPF*.zip").url' - | sed -r 's/.*IRPF([0-9.-]+)\.zip/\1/')
            echo ::set-output name=ARTIFACT_NAME::IRPF_v${{ steps.irpf.outputs.VERSION }}-${{ steps.vars.outputs.TODAY }}-${{ steps.vars.outputs.SHA_SHORT }}

      - name: Update metainfo.xml
        env:
          TZ: America/Sao_Paulo
        run: |
          sed -i "/<release /d; /<releases>/a\    <release date=\"$(date +'%Y-%m-%d')\" version=\"${{ steps.irpf.outputs.VERSION }}-${{ steps.vars.outputs.TODAY }}-${{ steps.vars.outputs.SHA_SHORT }}\">" "${{ steps.vars.outputs.REPO_NAME }}.metainfo.xml"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y flatpak-builder

      - name: Cache Flatpak SDK
        uses: actions/cache@v2
        with:
          key: forever
          path: |
            ~/.local/share/flatpak

      - name: Set up Flatpak
        run: |
          flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Build (x86_64)
        run: |
          flatpak-builder --user --arch=x86_64 --force-clean --install-deps-from=flathub --repo=repo/ --sandbox build/ "${{ steps.vars.outputs.REPO_NAME }}.yaml"

      - name: Bundle (x86_64)
        run: |
          flatpak build-bundle --arch=x86_64 repo/ "${{ steps.irpf.outputs.ARTIFACT_NAME }}-x86_64.flatpak" "${{ steps.vars.outputs.REPO_NAME }}" stable

      - name: Upload (x86_64)
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.irpf.outputs.ARTIFACT_NAME }}-x86_64.flatpak
          path: |
            ${{ steps.irpf.outputs.ARTIFACT_NAME }}-x86_64.flatpak
